---
layout: cv
title: Grant Orchard's CV
---
# Grant Orchard
University student seeking Data Science Degree with a minor in Statistics

<div id="webaddress">
<a href="https://www.linkedin.com/in/grant-orchard-5a9b86252/">LinkedIn</a>
</div>


## Currently

Studying Data Science with an interest in statistics


### Interests

Data Collection, Data Manipulation, Data Research


## Education

`2016-2020`
__Syracuse High School - Syracuse, NE__

`June 1661 - now`
__Brigham Young University-Idaho - Rexburg, ID__



## Skills

Skilled in R, Python, SQL

Fluent in French

Hard-working and willing to learn

## Occupation

`2022-2023`
__Support Center Phones Specialist__, Brigham Young University-Idaho

- Took phone calls daily
- Helped simplify the student experience

`2023-now`
__Support Center Hiring Manager__, Brigham Young University-Idaho

- Look over applications for potential candidates
- Interview for Phones and Chats/Emails Specialist Positions
- Select correct candidates for these positions
- Research retentiion to improve employee turnover rate



<!-- ### Footer

Last updated: May 2013 -->